version: '3.1'

networks:
    web_api:

services:
    postgres:
        image: postgres:15
        restart: always
        container_name: divider_postgres
        ports:
            - '5433:5432'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=divider_db
        volumes:
            - ./pgdata:/var/lib/postgres/data
        networks:
            - web_api
