version: '3.1'

networks:
  web_api:

services:
  postgres:
    image: postgres:15
    restart: always
    container_name: api_postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=api_core_db
    volumes:
      - ./pgdata:/var/lib/postgres/data
    networks:
      - web_api

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    restart: always
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    networks:
      - web_api

  kafka:
    image: confluentinc/cp-kafka:latest
    restart: always
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CREATE_TOPICS=test:1:1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    networks:
      - web_api
